libext2fs: fix 32-bit Windows build
_WIN32 is the standard macro to detect Windows, regardless of 32-bit or
64-bit.  _WIN64 is for 64-bit Windows only.  Use _WIN32 where _WIN64 was
incorrectly being used.

This fixes several 32-bit Windows build errors, for example this one:

plausible.c: In function ‘print_ext2_info’:
plausible.c:109:31: error: ‘unix_io_manager’ undeclared (first use in this function); did you mean ‘undo_io_manager’?
  109 |                               unix_io_manager,
      |                               ^~~~~~~~~~~~~~~
      |                               undo_io_manager

Fixes: 86b6db9f5a43 ("libext2fs: code adaptation to use the Windows IO manager")
Cc: Paulo Antonio Alvarez <pauloaalvarez@gmail.com>
Change-Id: I548b204edd1d7b30ddf9fa3a9c1020179d2cbae9
Signed-off-by: Eric Biggers <ebiggers@google.com>